//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradProjectV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consult()
        {
            this.ConsultAnswers = new HashSet<ConsultAnswer>();
        }
    
        public int ID { get; set; }
        public string ConsultQuestionTitle { get; set; }
        public string ConsultQuestionName { get; set; }
        public string AvailableFilePath { get; set; }
        public Nullable<int> QuestionerId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> QuestionDate { get; set; }
        public Nullable<int> ConsultTypeId { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ConsultType ConsultType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultAnswer> ConsultAnswers { get; set; }
    }
}
