//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradProjectV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacyWorker
    {
        public int ID { get; set; }
        public Nullable<int> PharmacyId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Pharamacy Pharamacy { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
