//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradProjectV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharamacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharamacy()
        {
            this.PharmacyMedicineRequests = new HashSet<PharmacyMedicineRequest>();
            this.PharmacyMedicineRequests1 = new HashSet<PharmacyMedicineRequest>();
        }
    
        public int ID { get; set; }
        public string PharmacyName { get; set; }
        public string PharmacyAddress { get; set; }
        public string PharmacyPhone { get; set; }
        public Nullable<int> PharmacyOwnerId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyMedicineRequest> PharmacyMedicineRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyMedicineRequest> PharmacyMedicineRequests1 { get; set; }
    }
}
