//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradProjectV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhMedicineRequestStatu
    {
        public int ID { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PhMedicineRequestStatusId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual PharmacyMedicineRequest PharmacyMedicineRequest { get; set; }
        public virtual Status Status { get; set; }
    }
}
