//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradProjectV5.Models.Previous_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficierMedicineRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeneficierMedicineRequest()
        {
            this.BMedicineRequestStatus = new HashSet<BMedicineRequestStatu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BeneficierId { get; set; }
        public Nullable<int> DonatorId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> RespondDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string RequestMedicineAmount { get; set; }
        public Nullable<int> LatestStatusId { get; set; }
    
        public virtual Beneficier Beneficier { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual Donator Donator { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BMedicineRequestStatu> BMedicineRequestStatus { get; set; }
    }
}
