//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradProjectV5.Models.Previous_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaint()
        {
            this.ComplaintStatus = new HashSet<ComplaintStatu>();
        }
    
        public int ID { get; set; }
        public string ComplaintDescription { get; set; }
        public Nullable<System.DateTime> ComplainDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LatestStautsId { get; set; }
        public Nullable<int> ComplaintRequsterId { get; set; }
        public Nullable<int> RespondDoctorId { get; set; }
        public string AvialableRespondNotes { get; set; }
        public string ComplaintFilePath { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintStatu> ComplaintStatus { get; set; }
    }
}
